return {
	-- "williamboman/mason-lspconfig.nvim",
	-- dependencies = {
	-- 	"williamboman/mason.nvim",
	-- 	"neovim/nvim-lspconfig"
	-- },
	--
	-- config = function ()
	-- 	require("mason").setup()
	-- 	require("mason-lspconfig").setup()
	--
	-- 	require("mason-lspconfig").setup {
	-- 	    ensure_installed = { "lua_ls", "rust_analyzer", "tsserver" },
	-- 	    handlers = {
	-- 		function(server_name)
	-- 			require("lspconfig")[server_name].setup({})
	-- 		end,
	-- 	    }
	-- 	}
	-- end
}
